config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
  collection do
    get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
    get :autocomplete_for_person
    post :bulk_edit, :bulk_update, :send_mails, :add_manager
    delete :bulk_destroy
    get 'calendar' => 'people_calendars#index'
    resources :holidays, except: :show, controller: :people_holidays, as: :people_holidays
  end

  member do
    get :manager
    get :autocomplete_for_manager
    delete :destroy_avatar
    get 'tabs/:tab' => 'people#show', :as => 'tabs'
    get 'load_tab' => 'people#load_tab', :as => 'load_tab'
    delete 'remove_subordinate' => 'people#remove_subordinate', :as => 'remove_subordinate'
  end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => 'tabs'
    get 'load_tab' => 'departments#load_tab', :as => 'load_tab'
  end

  get :org_chart, on: :collection
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries, except: [:index]

app/helpers/people_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleHelper

  def people_tabs(person)
    tabs = [
      { name: 'activity', partial: 'activity', label: l(:label_activity)},
      { name: 'files', partial: 'attachments', label: l(:label_attachment_plural)},
      { name: 'projects', partial: 'projects', label: l(:label_project_plural)}
    ]

    tabs << { name: 'subordinates', partial: 'subordinates', label: l(:label_people_subordinates)} if person.subordinates.any?
    tabs
  end

  def birthday_date(person)
    ages = person_age(person.age)
    if person.birthday.day == Date.today.day && person.birthday.month == Date.today.month
      "#{l(:label_today).capitalize} #{"(#{ages})" unless ages.blank?}".strip
    else
      "#{person.birthday.day} #{t('date.month_names')[person.birthday.month]} #{"(#{ages.to_i + 1})" unless ages.blank?}".strip
    end
  end

  def person_manager_full_name
    manager = @person.manager_id ? Person.find(@person.manager_id) : ''
    content_tag('span', manager, :class => 'manager')
  end

  def retrieve_people_query
    if params[:query_id].present?
      @query = PeopleQuery.find(params[:query_id])
      raise ::Unauthorized unless @query.visible?
      session[:people_query] = {:id => @query.id}
      sort_clear
    elsif api_request? || params[:set_filter] || session[:people_query].nil?
      # Give it a name, required to be valid
      @query = PeopleQuery.new(:name => "_")
      @query.build_from_params(params)
      session[:people_query] = {:filters => @query.filters, :group_by => @query.group_by, :column_names => @query.column_names}
    else
      # retrieve from session
      @query = PeopleQuery.find_by(id: session[:people_query][:id]) if session[:people_query][:id]
      @query ||= PeopleQuery.new(:name => "_", :filters => session[:people_query][:filters], :group_by => session[:people_query][:group_by], :column_names => session[:people_query][:column_names])
    end
  end

  # TODO: Perhaps, may move this function into redmine_crm gem
  def people_list_style
    list_styles = people_list_styles_for_select.map(&:last)
    if params[:people_list_style].blank?
      list_style = list_styles.include?(session[:people_list_style]) ? session[:people_list_style] : RedminePeople.default_list_style
    else
      list_style = list_styles.include?(params[:people_list_style]) ? params[:people_list_style] : RedminePeople.default_list_style
    end
    session[:people_list_style] = list_style
  end

  def people_list_styles_for_select
    list_styles = [[l(:label_people_list_excerpt), "list_excerpt"]]
  end

  def people_principals_check_box_tags(name, principals)
    s = ''
    principals.each do |principal|
      s << "<label>#{ check_box_tag name, principal.id, false, :id => nil } #{principal.is_a?(Group) ? l(:label_group) + ': ' + principal.to_s : principal}</label>\n"
    end
    s.html_safe
  end

  def people_principals_radio_button_tags(name, principals)
    s = ''
    principals.each do |principal|
      s << "<label>#{ radio_button_tag name, principal.id, false, :id => nil } #{principal.is_a?(Group) ? l(:label_group) + ': ' + principal.to_s : principal}</label>\n"
    end
    s.html_safe
  end

  def change_status_link(person)
    return unless User.current.allowed_people_to?(:edit_people, person) && person.id != User.current.id && !person.admin
    url = {:controller => 'people', :action => 'update', :id => person, :page => params[:page], :status => params[:status], :tab => nil}

    if person.locked?
      link_to l(:button_unlock), url.merge(:person => {:status => User::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    elsif person.registered?
      link_to l(:button_activate), url.merge(:person => {:status => User::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    elsif person != User.current
      link_to l(:button_lock), url.merge(:person => {:status => User::STATUS_LOCKED}), :method => :put, :class => 'icon icon-lock'
    end
  end

  def person_tag(person, options={})
    avatar_size = options.delete(:size) || 16
    if person.visible? && !options[:no_link]
      person_avatar = link_to(avatar(person, size: avatar_size, only_path: options[:only_path]), person_path(person), id: 'avatar')
      person_name = link_to(person.name, person_path(person))
    else
      person_avatar = avatar(person, size: avatar_size, only_path: options[:only_path])
      person_name = person.name
    end

    case options.delete(:type).to_s
    when "avatar"
      person_avatar.html_safe
    when "plain"
      person_name.html_safe
    else
      content_tag(:span, "#{person_avatar} #{person_name}".html_safe, :class => "person")
    end
  end

  def render_people_tabs(tabs)
    if tabs.any?
      render :partial => 'common/people_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end

  def cleaned_phone(phone)
    phone.scan(/[\d+()-]+/).join
  end

  def metric_deviation_html(previous, current, options = {})
    return if previous.blank? || current.blank?

    content_tag :span, class: 'change', title: deviation_label(previous, current, options) do
      if current == previous
        '0%'
      else
        content_tag(:span, '', class: arrow_classes(previous, current, options)) +
          "#{calculate_progress(previous, current).round}%"
      end
    end
  end

  def arrow_classes(previous, current, options = {})
    prefix = options.fetch(:positive_metric, true) ? '' : 'mirror_'
    ['caret', (current > previous) ? "#{prefix}pos" : "#{prefix}neg"]
  end

  def deviation_label(previous, current, options = {})
    format = options.fetch(:format, :time)
    deviation = (current - previous).abs

    if format == :time
      previous = hours_with_minutes(previous)
      deviation = hours_with_minutes(deviation)
    else
      previous = previous.round
      deviation = deviation.round
    end

    result = ''
    result << "#{label_period(options[:period])}\n" if options[:period]
    result << "#{l(:label_previous)}: #{previous}\n#{l(:label_people_deviation)}: #{deviation}"
    result.html_safe
  end

  def label_period(period, date_format = '%m.%d')
    "#{l(:label_people_period)}: #{period.first.strftime(date_format)} - #{period.last.strftime(date_format)}"
  end

  def hours_with_minutes(time, label_hour = l(:label_people_hour), label_minute = l(:label_people_minute))
    "#{time.to_i}#{label_hour} #{(60 * (time % 1)).round}#{label_minute}".html_safe
  end

  def options_for_select2_people(selected)
    if selected && (person = Person.all_visible.find_by_id(selected))
      options_for_select([[person.name, person.id]], selected)
    end
  end
end

app/views/people/_attributes.html.erb
<div id="attributes">

<h3><%= l(:label_people_person) %></h3>

<table class="person attributes vcard">
  <%= call_hook(:view_people_sidebar_attributes_top) %>
	<tr>
		<th class = "first-name"><%= l(:field_name) %>:</th><td class="name fn "><%= @person.firstname %></td>
	</tr>
	<tr>
		<th class = "middle-name"><%= l(:label_people_middlename) %>:</th><td class="name mn "><%= @person.middlename %></td>
	</tr>
	<tr>
		<th class = "last-name"><%= l(:field_lastname) %>:</th><td class="name ln "><%= @person.lastname %></td>
	</tr>
	<% if !@person.job_title.blank? %>
	<tr> <th class = "job_title"><%= l(:label_people_job_title) %>:</th><td class="job_title title"><%= @person.job_title %></td></tr>
	<% end %>
	<% if !@person.manager.blank? %>
		<tr>
		<th class = "manager"><%= l(:label_people_manager) %>:</th><td class="manager title"><%= link_to_user(@person.manager) %></td></tr>
	<% end %>
	<tr>
		<th class = "address"><%= l(:label_people_address) %>:</th>
		<td class="address adr"><%= @person.address %>
				<% if !@person.address.blank? %>
					<br>
					<%= link_to l(:label_people_show_on_map), "http://maps.google.com/maps?f=q&q=#{h @person.address.gsub("\r\n"," ").gsub("\n"," ")}+(#{h @person.name})&ie=UTF8&om=1"%>
				<% end %>
		</td>
		</tr>
	<tr class = "tel">
		<th class = "phone"><%= l(:label_people_phone_plural) %>:</th>
		<td class = "phones">
		<% @person.phones.each do |phone| %>
			<span  class="value"><%= h phone %> <br></span>
		 <% end %>
		</td>
	</tr>
	<tr class = "email">
		<th><%= l(:field_mail) %>:</th>
		<td>
			<%= mail_to @person.email  %>
		</td>
	</tr>
 	<% unless @person.skype.blank? %>
	<tr>
	  <th class = "skype"><%= l(:label_people_skype) %>:</th>
	  <td class="skype icon icon-skype"><%= link_to @person.skype, "skype:#{@person.skype}?call" %></td>
	</tr>
	<% end %>
  <% unless @person.twitter.blank? %>
	<tr>
	  <th class = "twitter"><%= l(:label_people_twitter) %>:</th>
	  <td class="twitter icon icon-twitter"><%= link_to @person.twitter, "http://twitter.com/" + @person.twitter %></td>
	</tr>
  <% end %>
  <% unless @person.facebook.blank? %>
	<tr>
	  <th class = "facebook"><%= l(:label_people_facebook) %>:</th>
	  <td class="facebook icon icon-facebook"><%= link_to @person.facebook.gsub(/^.*facebook.com\//, ''), "http://facebook.com/#{@person.facebook}" %></td>
	</tr>
  <% end %>
  <% unless @person.linkedin.blank? %>
	<tr>
	  <th class = "linkedin"><%= l(:label_people_linkedin) %>:</th>
	  <td class="linkedin icon icon-linkedin"><%= link_to @person.name, "http://www.linkedin.com/profile/view?id=#{@person.linkedin}"%></td>
	</tr>
  <% end %>

	<% unless @person.birthday.blank? %>
	<tr> <th class = "birthday"><%= l(:label_people_birthday) %>:</th><td class="birthday bday" title="<%= "#{format_date(@person.birthday)}" %>"><%= "#{@person.birthday.day} #{t('date.month_names')[@person.birthday.month]}"%></td> </tr>
	<% unless RedminePeople.hide_age? %>
		<tr> <th class = "age"><%= l(:label_people_age) %>:</th><td class="ega"><%= @person.age %></td> </tr>
	<% end %>
	<% end %>

	<% @person.custom_values.each do |custom_value| %>
		<% if !custom_value.value.blank? && (User.current.admin? || custom_value.custom_field.visible?) %>
		<tr> <th class = "custom_field"><%= custom_value.custom_field.name%>:</th><td> <%=h show_value(custom_value) %></td> </tr>
		<% end %>
	<% end %>

  <tr> <th class = "registered_on"> <%=l(:label_registered_on)%>:</th><td class="registered_on"> <%= format_date(@person.created_on) %></td> </tr>
  <% unless @person.last_login_on.nil? %>
	<tr> <th class = "last_login_on"> <%=l(:field_last_login_on)%>:</th><td class="last_login_on"> <%= format_time(@person.last_login_on) %></td> </tr>
  <% end %>

	<%= call_hook(:view_people_sidebar_attributes_bottom) %>

</table>

</div>

app/views/people/_form.html.erb
<div class = "box tabular" id="person_data">
  <% if PeopleInformation::modified_system_fields?(@person) %>
    <p id="issue_is_private_wrap">
      <%= hidden_field_tag 'person[information_attributes][is_system]', 0, :id => nil %>
      <%= check_box_tag 'person[information_attributes][is_system]', 1, @person.is_system %><label class="inline" for="person_information_attributes_is_system" id="person_is_system_label"><%= l(:label_people_is_system) %></label>
    </p>
  <% end %>
  <p class="avatar" id="watchers">
    <%= avatar(@person, :size => "64", :height => 64, :width => 64, :style => "vertical-align: middle;") %>
    <%= link_to image_tag('delete.png'), destroy_avatar_person_path(@person),
                                           :confirm => l(:text_are_you_sure),
                                           :method => :delete,
                                           :class => 'delete',
                       :style => "vertical-align: middle;",
                                           :title => l(:button_delete) unless @person.avatar.blank? %>
  </p>
  <p><%= label_tag l(:label_people_avatar) %> <%= file_field_tag 'person_avatar[file]', :size => 30, :id => nil  -%> </p>
  <p><%= f.text_field :firstname, :required => true %></p>

  <%= f.fields_for :information do |information| %>
    <p><%= information.text_field :middlename, :label => l(:label_people_middlename) %></p>
    <p><%= f.text_field :lastname, :required => true %></p>

    <% if @person.available_managers.any? || @person.new_record? %>
      <p id="person_information_attributes_manager_id_wrap">
        <label><%= l(:label_people_manager) %></label>
        <%= select2_tag 'person[information_attributes][manager_id]',
                        options_for_select(@person.available_managers.where(id: information.object.manager_id).map { |manager| [manager.name, manager.id] }, information.object.manager_id),
                        url: autocomplete_for_manager_person_path(id: f.object.id || 'new'),
                        placeholder: '',
                        format_state: 'formatStateWithAvatar',
                        allow_clear: true %>
      </p>
    <% end %>

    <% if @person.id != User.current.id %>
    <p><%= f.select :status, options_for_select([[l(:status_active), User::STATUS_ACTIVE], [l(:status_locked), User::STATUS_LOCKED]], @person.status.to_s) %></p>
    <% end %>

    <% unless @departments.blank? %>
      <p><%= information.select :department_id, department_tree_options_for_select(@departments,  :selected => @person.department_id), :include_blank => true, :label => l(:label_people_department) %></p>
    <% end %>
    <p><%= information.select :gender, Person.genders, :label => l(:label_people_gender)%></p>
    <p><%= information.text_field :appearance_date, :size => 12, :label => l(:label_people_appearance_date), type: 'date', value: @person.appearance_date.try(:to_date) %><%= calendar_for('person_information_attributes_appearance_date') %> </p>
    <p><%= information.text_field :birthday, :size => 12, :label => l(:label_people_birthday), type: 'date', value: @person.birthday.try(:to_date) %><%= calendar_for('person_information_attributes_birthday') %> </p>
    <p><%= information.text_field :job_title, :label => l(:label_people_job_title) %></p>
    <p><%= f.text_field :mail, :required => true %></p>
    <p><%= information.text_area :address, :label=>l(:label_people_address), :rows => 5 -%></p>

    <div id="phones_fields">
      <p>
        <%= information.text_field :phone, :label => l(:label_people_phone), :size => 80 -%>
        <br>
        <em><%= l(:text_comma_separated) %></em>
       </p>
    </div>

    <p><%= information.text_field :skype, :label => l(:label_people_skype) -%></p>
    <p><%= information.text_field :facebook, :label => l(:label_people_facebook) + ' ID'-%></p>
    <p><%= information.text_field :twitter, :label => l(:label_people_twitter) -%></p>
    <p><%= information.text_field :linkedin, :label => l(:label_people_linkedin) + ' ID' -%></p>

    <% custom_field_values = @person.custom_field_values.find_all {|v| User.current.admin? || v.custom_field.editable?} %>
    <div class="splitcontent">
      <div class="splitcontentleft">
      <% i = 0 %>
      <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
      <% custom_field_values.each do |value| %>
        <p><%= custom_field_tag_with_label :person, value, :required => value.custom_field.is_required? %></p>
      <% if i == split_on -%>
      </div><div class="splitcontentright">
      <% end -%>
      <% i += 1 -%>
      <% end -%>
      </div>
    </div>

    <p class  = "notes"><%= information.text_area :background , :cols => 80, :rows => 8, :class => 'wiki-edit', :label => l(:label_people_background)  %></p>
    <%= wikitoolbar_for 'person_information_attributes_background' %>
  <% end %>
</div>

app/views/people/_list_excerpt.html.erb
<%= form_tag({}, :data => {:cm_url => context_menu_people_path}) do %>
<%= hidden_field_tag 'back_url', url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params) %>
<div class="autoscroll">
    <table class="people index">
    <tbody>
    <% previous_group = false %>
    <% @people.each do |person| %>
        <% if @query.grouped? && (group = @query.group_by_column.value(person)) != previous_group %>
          <% reset_cycle %>
          <tr class="group open">
            <td colspan="<%= @query.columns.size + 2 %>">
              <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
              <%= group.blank? ? 'None' : column_content(@query.group_by_column, person) %> <span class="count">(<%= @people_count_by_group[group] %>)</span>
              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
            </td>
          </tr>
          <% previous_group = group %>
        <% end %>

       <tr class="hascontextmenu">
            <td class="checkbox">
                <%= check_box_tag "ids[]", person.id, false %>
            </td>
            <td class="avatar">
                <%= avatar(person, :size => "32", :height => 32, :width => 32) %>
            </td>
            <td class="name">
                <h1><%= link_to person.name, person_path(person) %></h1>
                <h2>
                    <%= mail_to person.mail %>
                    <div><%= person.phones.first %></div>
                </h2>
            </td>
            <td class="info">
                <div class="title_and_company" >
                    <%= h person.job_title %>
                    <% if person.department %>
                        <%= " #{l(:label_people_at_department)} "  %>
                        <%= person.department %>
                   <% end %>
                 </div>
                <div class="tags">
                </div>
            </td>
        </tr>

    <% end %>
    </tbody>
    </table>
 </div>
 <% end %>

app/views/people/_managers.html.erb
<h3 class="title"><%= l(:label_people_choose_manager) %></h3>

<%= form_tag(add_manager_people_path,
             :remote => true,
             :method => :post,
             :id => 'new-manager-form',
             :class => 'select-users') do %>

    <p><%= label_tag 'user_search', l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>
    <%= javascript_tag "observeSearchfield('user_search', 'users_for_manager', '#{ escape_javascript url_for(:controller => :people, :action => :autocomplete_for_manager, :id => person) }')" %>

    <fieldset>
      <div id="users_for_manager" >
        <%= people_principals_radio_button_tags('id', managers) %>
      </div>
    </fieldset>

    <p class="buttons">
      <%= submit_tag l(:button_add), :name => nil, :onclick => "hideModal(this);" %>
      <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
    </p>
<% end %>

app/views/people/_person_birthday.html.erb
<div class="person">
  <div class="image"><%= link_to avatar(person_birthday, size: '32'), person_path(person_birthday), id: 'avatar' %></div>
  <div class="data">
    <h4 class="name"><%= link_to person_birthday.name, person_path(person_birthday) %></h4>
    <p class="info" title="<%= format_date(person_birthday.birthday) %>"><%= birthday_date(person_birthday) %></p>
  </div>
</div>

app/views/people/_person_data.html.erb
<table class="person_data" id="person_data_<%= person_data.id %>">
  <tr>
    <td class="avatar"><%= link_to avatar(person_data, :size => "32"), person_path(person_data), :id => "avatar" %></td>
    <td class="name">
      <h4 class="contacts_header">
        <%= link_to person_data.name, person_path(person_data) %>
      </h4>
      <p>
          <span class="job_title"><%= person_data.job_title %></span>
      </p>
    </td> 
  </tr>
</table>

app/views/people/_projects.html.erb
<% unless @person.all_visible_memberships.empty? %>
<ul>
<% @person.all_visible_memberships.each do |membership| %>
  <li><%= link_to_project(membership.project) %>
    (<%=h membership.roles.sort.collect(&:to_s).join(', ') %>, <%= format_date(membership.created_on) %>)</li>
<% end %>
</ul>
<% end %>

app/views/people/_sidebar.html.erb
<% content_for :sidebar do %>

    <% unless true || Department.all_visible_departments.blank? %>
        <div id="people_departments">
          <h3><%= l(:label_department_plural) %></h3>
          <%= department_tree_links(Department.all_visible_departments) %>
        </div>
    <% end %>

    <% if Person.all_visible_next_birthdays.present? %>
    <div id="next_birthdays" class="person-data">
      <h3><%= l(:label_people_next_birthdays) %></h3>
      <%= render :partial => 'people/person_birthday', :collection => Person.all_visible_next_birthdays %>
    </div>
    <% end %>

    <% if PeopleHoliday.next_holidays.present? %>
    <div id="next_holidays">
      <h3><%= l(:label_people_holidays_next) %></h3>
      <%= render :partial => 'people_holidays/next_holidays' %>
    </div>
    <% end %>

    <% if Person.all_visible_new_people.present? %>
    <div id="new_people">
      <h3><%= l(:label_people_new_people) %></h3>
      <%= render :partial => 'people/person_data', :collection => Person.all_visible_new_people %>
    </div>
    <% end %>

<% end %>

app/views/people/_subordinates.html.erb
<div id="company_contacts">
  <div class="contextual">
    <% if User.current.allowed_people_to?(:add_people, @person) %>
      <%= link_to l(:label_user_new), {:controller => 'people', :action => 'new', :manager_id => @person.id} %>
    <% end %>
  </div>
  <h3><%= l(:label_people_contact_plural) %></h3>

  <%= render :partial => 'person_data', :collection => @person.all_visible_subordinates(params[:page], @limit) %>
  <div style="clear:both;"> </div>
</div>

app/views/people/autocomplete_for_person.js.erb
<%= raw @people.map { |person|
      { id: person.id,
        text: person.name.html_safe,
        avatar: avatar(person, size: 16) }
    }.to_json
%>

app/views/people/context_menu.html.erb
<ul>

  <% if @person.present? %>
    <li><%= context_menu_link l(:button_edit), {:controller => 'people', :action => 'edit', :id => @person}, :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
  <% else %>
  <% end %>

</ul>

app/views/people/edit.html.erb
<div class="contextual">
    <%= link_to(l(:button_people_edit_profile), edit_user_path(@person), :class => 'icon icon-edit') if User.current.admin? %>
</div>

<h2><%= l(:label_people_edit_person) %></h2>

<%= labelled_form_for :person, @person,
                             :url => {:action => 'update', :id => @person},
                             :html => { :multipart => true, :method => :put, :id => "person_form" } do |f|  %>
  <%= error_messages_for 'person' %>

  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :sidebar do %>
<% end %>

<% content_for :header_tags do %>
  <%= select2_assets %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= robot_exclusion_tag %>
<% end %>

app/views/people/index.html.erb
<div class="contextual">
    <%= link_to l(:label_user_new), {:controller => 'people', :action => 'new', :department_id => @department}, :class => 'icon icon-add' if User.current.allowed_people_to?(:add_people, @person) %>
    <%= call_hook(:view_people_action_menu) %>
</div>

<% html_title(@query.new_record? ? l(:label_people) : @query.name) %>

<div class="filters">
	<%= form_tag({:contoller => "people", :action => "index"}, :method => :get,  :id => "query_form") do %>
    <%= hidden_field_tag 'set_filter', '1' %>

    <script type="text/javascript">
       jQuery(function($) {
          // when the #search field changes
          $("#search").observe_field(2, function() {
            var form = $("#query_form"); // grab the form wrapping the search bar.
            var url = form.attr("action");
            form.find('[name="c[]"] option').each(function(i, elem){
              $(elem).attr('selected', true)
            });
            var formData = form.serialize();
            form.find('[name="c[]"] option').each(function(i, elem){
              $(elem).attr('selected', false)
            });
            $.get(url, formData, function(data) { // perform an AJAX get, the trailing function is what happens on successful get.
                $("#people_list").html(data); // replace the "results" div with the result of action taken
            });
          });
        });
    </script>

    <h2 class="people_header">
        <span id='scope_header' class="scope_title">
        <%= @query.new_record? ? l(:label_people) : @query.name %>
        </span>

        <span class="live_search">
            <%= text_field_tag(:search, params[:search], :autocomplete => "off", :class => "live_search_field", :placeholder => l(:label_people_search) ) %>
        </span>
    </h2>
	<% end %>
</div>

<div id="people_list">
<% if @people.blank? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
    <%= render :partial => people_list_style %>
    <span class="pagination"><%= pagination_links_full @people_pages, @people_count %></span>
<% end %>
</div>

<% html_title l(:label_people) %>

<% if Redmine::VERSION.to_s >= '3.4' || Redmine::VERSION::BRANCH != 'stable' %>
    <%= context_menu %>
<% else %>
    <%= context_menu url_for( {:controller => "people", :action => "context_menu"} ) %>
<% end %>

<%= render :partial => 'people/sidebar', :locals => {:tags => @tags} %>

<% content_for :header_tags do %>
  <%= select2_assets %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <meta name = "format-detection" content = "telephone=no">
<% end %>

app/views/people/load_tab.js.erb
<%
    @tab = params[:tab_name]
    @partial = params[:partial]
%>
$('#tab-placeholder-<%= @tab %>').html("<%= j(render :partial => @partial) %>");